core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('projects/', include('projects.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='projects'),
    path('<str:slug>', views.project, name='project'),
]

main/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.db.models import F
from django.utils.text import slugify
import uuid

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=256)
    subtitle = models.CharField(max_length=256, null=True, blank=True)
    thumbnail = models.CharField(max_length=256, blank=True)
    favicon = models.CharField(max_length=256, null=True, blank=True)
    hero = models.CharField(max_length=256, null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    year = models.IntegerField(null=True, blank=True)
    slug = models.SlugField(max_length=128, unique=True, blank=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    tags = models.ManyToManyField('Tag', blank=True)
    urls = models.JSONField(null=True, blank=True)
    data = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.title and len(self.title) > 0:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    @property
    def website_url(self):
        if self.urls and 'live_website' in self.urls:
            return self.urls['live_website']

    @property
    def source_code_url(self):
        if self.urls and 'source_code' in self.urls:
            return self.urls['source_code']

class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=128, unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.name and len(self.name) > 0:
            self.name = self.name.lower().strip()
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Gallery(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=256, null=True, blank=True)
    order = models.IntegerField(default=1)
    data = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = [F('order').asc(nulls_last=True)]

    def __str__(self):
        if self.title:
            return f"{str(self.project)} - {self.title}"
        else:
            return str(self.project)


class GalleryItem(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    title = models.CharField(max_length=256, null=True, blank=True)
    order = models.IntegerField(default=1)
    caption = models.CharField(max_length=256, null=True, blank=True)
    url = models.CharField(max_length=256, null=True, blank=True)
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    thumb = models.CharField(max_length=256, null=True, blank=True)
    data = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = [F('order').asc(nulls_last=True)]

    def __str__(self):
        if self.title:
            return f"{str(self.gallery)} - {self.title}"
        else:
            return str(self.gallery)

main/views.py
from django.shortcuts import render
from projects.models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    context = {'projects': projects}
    return render(request, 'main/home.html', context)

projects/views.py
from django.shortcuts import render
from .models import Project, Gallery


def index(request):
    projects = Project.objects.all()
    context = { 'projects': projects }

    return render(request, 'projects/index.html', context)

def project(request, slug):
    project = Project.objects.get(slug=slug)
    galleries = Gallery.objects.filter(project_id=project.id)
    context = { 'project': project, 'galleries': galleries }

    return render(request, 'projects/project_details.html', context)

main/templates/main/home.html
{% extends 'app.html' %}
{% block title %}Kyle Bollinger{% endblock %}


{% block content %}
<section class="hero hero--main">
  <div class="wrap">
    <hgroup>
      <h1>Hello, I'm <span>Kyle.</span></h1>
      <h3>Seasoned software developer and web designer with a knack for crafting easy to use digital solutions</h3>
    </hgroup>
    <figure><img src="https://kboll.s3.amazonaws.com/images/kyle-headshot-800.webp"></figure>
  </div>
</section>

{% if projects %}
<section class="py-4">
  <div class="container-xxl">
    <hgroup class="text-center">
      <h2 class="colorize-title mb-3">Work</h2>
      <h4>Here's some of the things I've been up to</h4>
    </hgroup>
    <div class="projects my-5">
      {% for project in projects %}
        {% include 'projects/partials/project.html' with project=project %}
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}

{% endblock %}

projects/templates/details/body.html
<section class="project-details">
  <div class="container">
    <article>
      {{ project.body|safe }}
    </article>
  </div>
</section>

projects/templates/details/galleries.html
{% if galleries %}
<section>
  <div class="container">
    {% for gallery in galleries %}
    {% if galleries|length > 1 %}
      <h2>{{ gallery.title }}</h2>
    {% else %}
      <h2>UI Screenshots</h2>
    {% endif %}
    <div class="pswp-gallery">
      {% for item in gallery.galleryitem_set.all.values %}
        <figure class="pswp-gallery__item">
          <a 	href="{{ item.url }}"
              data-pswp-width="{{ item.width }}"
              data-pswp-height="{{ item.height }}"
              data-cropped="true"
              target="_blank"
              >
            <div class="gallery--image" style="background-image: url('{% if item.thumb %}{{ item.thumb }}{% else %}{{ item.url }}{% endif %}')" alt="{{item.title}}"></div>
          </a>
          {% if item.caption %}
            <figcaption class="hidden-caption-content">
              <h6>{{ item.title }}</h6>
              <p>{{ item.caption }}</p>
            </figcaption>
          {% endif %}
        </figure>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
</section>
{% endif %}

projects/templates/details/hero.html
<section class="hero hero--project">
  <div class="container">
    <hgroup>
      <h1>{{ project.title }}</h1>
      {% if project.subtitle %}<h2>{{ project.subtitle }}</h2>{% endif %}
    </hgroup>
    {% if project.summary %}<h4>{{ project.summary }}</h4>{% endif %}

    {% if project.website_url or project.source_code_url %}
    <div class="button-group">
      {% if project.website_url %}
      <a href = "{{ project.website_url }}" target="_blank" class="button button--secondary">Live Website</a>
      {% endif %}

      {% if project.source_code_url %}
      <a href = "{{ project.source_code_url }}" target="_blank" class="button button--secondary">Source Code</a>
      {% endif %}
    </div>
    {% endif %}
  </div>

  {% if project.hero %}
  <figure class="hero--image">
    <div class="hero--overlay"></div>
    <img src="{{ project.hero }}" alt="{{ project.title }}">
  </figure>
  {% endif %}
</section>

projects/templates/projects/index.html
{% extends 'app.html' %}
{% block title %}Kyle Bollinger | Projects{% endblock %}


{% block content %}
<section>
  <div class="container-xxl">
    <h1>Projects</h1>
    <div class="projects">
      {% for project in projects %}
      {% include 'projects/partials/project.html' %}
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

projects/templates/projects/partials/project.html
<article class="project">
    <div class="col col-left">
        <h3 class="m-0">{{ project.title }}</h3>
        <p>{{ project.summary }}</p>
        {% if project.tags.all %}
        <div class="badges">
            {% for tag in project.tags.all %}
            <span class="badge">{{ tag.name }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <a href="{% url 'project' slug=project.slug %}" class="mt-5 button button--outline-white">View Details</a>
    </div>
    <div class="col col-right">
        <figure>
            <img src="{{ project.thumbnail }}">
        </figure>
    </div>
</article>

projects/templates/projects/project.html
<article class="project">
    <div class="col col-left">
        <h3 class="m-0">{{ project.title }}</h3>
        <p>{{ project.summary }}</p>
        {% if project.tags.all %}
        <div class="badges">
            {% for tag in project.tags.all %}
            <span class="badge">{{ tag.name }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <a href="{{ project.url }}" class="mt-5 button button--outline-white">View Details</a>
    </div>
    <div class="col col-right">
        <figure>
            <img src="{{ project.thumbnail }}">
        </figure>
    </div>
</article>

projects/templates/projects/project_details.html
{% extends 'app.html' %}
{% block title %}{{ project.title }}{% endblock %}

{% block body_class %}unified details{% endblock %}
{% block content %}


{% include 'details/hero.html' %}
{% include 'details/body.html' %}
{% include 'details/galleries.html' %}


{% endblock %}

templates/app.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'layout/head.html'%}
    {% render_bundle 'app' %}
  </head>

  <body class="{% block body_class %}{% endblock %}">
    <div class="bg-right"></div>
    <div class="bg-left"></div>
    {% include 'layout/navbar.html' %}
    <main class="{% block main_class %}{% endblock %}">
      {% block content %}
      {% endblock %}
    </main>
    {% include 'layout/footer.html' %}
    {% render_bundle 'main' %}
  </body>
</html>

templates/includes/favicon.html
{% load static %}
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

templates/includes/svg/logo.html
<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 48"><mask id="a" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="192" height="48"><path d="M0 2C0 .9.9 0 2 0h50a2 2 0 0 1 2 2v44a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2Z" fill="#121212"/><path d="M13 34.7 23.7 24 13 13.3M28 35h12" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><path d="M84.3 43.8 77 30l-3 2.7v11.1H66V3.6h8V24l9-8.2h10.5L83 25.1l10.6 18.7h-9.3ZM126.6 29.7c0 9.7-6.1 14.6-12.6 14.6-3.3 0-6-1.4-7.6-3.5v3h-7.5V3.6h8v14.1c1.8-1.5 4.2-2.4 7-2.4 6.7 0 12.7 4.9 12.7 14.4Zm-19.7 1.8c0 3.4 2.6 5.6 5.6 5.6 3.1 0 6-2.3 6-7.4 0-5-2.9-7.2-6-7.2-3 0-5.5 2-5.6 5.5v3.5ZM146.2 44.4c-7.5 0-14.3-5-14.3-14.7a14 14 0 0 1 14.3-14.5c7.6 0 14.4 5 14.4 14.5s-7 14.7-14.4 14.7Zm0-7c3.4 0 6.2-2.7 6.2-7.7 0-4.9-3-7.4-6.2-7.4-3.1 0-6.1 2.5-6.1 7.4 0 5 3 7.6 6.1 7.6ZM167.3 43.8V3.6h8v40.2h-8ZM184 43.8V3.6h8v40.2h-8Z" fill="#0A0A0A"/></mask><g mask="url(#a)"><path fill="url(#b)" d="M0 0H192V48H0z"/><path d="M14 34.7 24.7 24 14 13.3M29 35h12" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></g><defs><linearGradient id="b" x1="0" y1="20.5" x2="192" y2="20.5" gradientUnits="userSpaceOnUse"><stop stop-color="#5EFCE8"/><stop offset="1" stop-color="#736EFE"/></linearGradient></defs></svg>

templates/includes/svg/terminal.html
<svg width="54" height="48" viewBox="0 0 54 48" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="54" height="48" rx="4" fill="url(#primary-gradient-x)"/><path d="M13 34.6666L23.6667 24L13 13.3333" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><path d="M28 35L40 35" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><defs><linearGradient id="primary-gradient-x" x1="-1.64146e-07" y1="20.5" x2="54" y2="20.5" gradientUnits="userSpaceOnUse"><stop stop-color="#5EFCE8"/><stop offset="1" stop-color="#736EFE"/></linearGradient></defs></svg>

templates/layout/footer.html
<footer>
  <div class="container-xxl">
    <nav class="global-nav">
      <div class="logo">
        {% include 'includes/svg/terminal.html' %}
      </div>

      <div class="links">
        <ul class="nav">
          <li><a href="https://github.com/kylebollinger" target="_blank">Github</a></li>
          <li><a href="https://linkedin.com/in/kylebollinger" target="_blank">LinkedIn</a></li>
          <li><a href="https://kboll.s3.amazonaws.com/bollinger-kyle-resume.pdf" target="_blank">Resume</a></li>
        </ul>
      </div>

      <div class="copy">
        <p class="m-0">&copy; Kyle Bolliger {% now 'Y' %}</p>
      </div>
    </nav>
  </div>
</footer>

templates/layout/head.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatable" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %}</title>
<meta name="description" content="A quick learner who excels in a fast-paced, demanding work atmosphere requiring the ability to multitask and be resourceful on the fly.">
{% include 'includes/favicon.html' %}
<style>@import url('https://fonts.googleapis.com/css2?family=Onest:wght@300;400;500;700&display=swap');</style>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-M9NG75SLB0"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-M9NG75SLB0');</script>

templates/layout/navbar.html
{% comment %} Set URL Variables {% endcomment %}
{% url 'projects' as projects_url %}


<header>
  <div class="container-xxl">
    <nav class="global-nav">
      <a class="global-nav--logo" href="{% url 'home' %}">
        {% include 'includes/svg/logo.html' %}
      </a>
      <ul class="nav global-nav--nav">
        <li><a class="{% if request.path == projects_url %}active{% endif %}" href="{{ projects_url }}">Projects</a></li>
        <li><a class="" href="https://kboll.s3.amazonaws.com/bollinger-kyle-resume.pdf" target="_blank">Resume</a></li>
      </ul>
      {% comment %} <button type="button" aria-label="Open global menu" aria-controls="contact-menu" aria-expanded="false" class="global-nav--burger" data-global-nav-btn></button> {% endcomment %}
    </nav>
  </div>
</header>

templates/main/home.html
{% extends 'app.html' %}
{% block title %}Kyle Bollinger{% endblock %}


{% block content %}
<section>
  <div class="container">
    <h1>Hello, I'm <span>Kyle.</span></h1>
    <h3>Seasoned software developer and web designer with a knack for crafting easy to use digital solutions.</h3>
  </div>
</section>

{% if projects %}
<section>
  <div class="container">
    <hgroup>
      <h2>Work</h2>
      <h4>Here's what I've been up to.</h4>
    </hgroup>
    <div class="projects">
      {% for project in projects %}
      <article class="project">
        <a href="{{ project.url }}" class="stretch-link"></a>
        <figure style="background-image: url('{{ project.thumbnail }}')" alt="{{ project.title }}"></figure>
        <h3>{{ project.title }}</h3>
        <p>{{ project.summary }}</p>
        {% if project.tags.all %}
        {% for tag in project.tags.all %}
          <span class="badge">{{ tag.name }}</span>
        {% endfor %}
        {% endif %}
      </article>
      {% endfor %}
    </div>
  </div>
</section>
{% endif %}

{% endblock %}